[build]
builder = "NIXPACKS"
installCommand = "bun install"
buildCommand = "bunx prisma generate && bunx prisma migrate deploy"

[deploy]
startCommand = "bun src/index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
